# 18. Linear Transformations

In [1]:
import numpy as np    # Import the NumPy module
print(np.version.version)   # Check the currently installed NumPy version

1.23.2


In [2]:
# Declaration of a basic data type - array in NumPy
a = np.array([[1, 2, 3], [4, 5, 6]])   
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
# Array dimensions
print("The number of dimensions of array a is: ", a.ndim)  

The number of dimensions of array a is:  2


In [4]:
# Length of each dimension of the array
print("The length of each dimension of array a is: ", a.shape)  

The length of each dimension of array a is:  (2, 3)


In [5]:
# Total number of elements in the array
print("The total number of elements in array a is: ", a.size)  

The total number of elements in array a is:  6


In [6]:
# Type of elements in the array
print("The type of elements in array a is: ", a.dtype)  

The type of elements in array a is:  int64


In [7]:
# Create an array using the arange function (start, end, step)
b = np.arange(0, 20, 5)     
print(b)

[ 0  5 10 15]


In [8]:
# Change the shape of the array
b.reshape(2, 2)         

array([[ 0,  5],
       [10, 15]])

In [9]:
# Create an array using the linspace function (start, end, number of elements)
c = np.linspace(0, 2, 10)   
print(c)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [10]:
# Quickly create an array with all elements as 0
zero_arr = np.zeros((3,4))   
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
one_arr = np.ones((2,3,4), dtype=np.int64)   # Quickly create an array with all elements as 1, and set the type to integer
print(one_arr)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [12]:
eye_arr = np.eye(3)   # Quickly create an identity matrix
print(eye_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[0:4])      
print(arr[0:4:2])

[1 2 3 4]
[1 3]


In [14]:
# Traversing each element in the array
for ele in arr:     
    print(ele)

1
2
3
4
5
6


In [15]:
# Changing the shape of the arr array
arr = arr.reshape(2,3)     
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
# Selecting the first subsequence of the first dimension in the arr array
print(arr[0,:])            

[1 2 3]


In [17]:
# Selecting the first element in the first subsequence of the first dimension in the arr array
print(arr[0, 0])           

1


In [18]:
# Selecting all elements in the second subsequence of the second dimension in the arr array
print(arr[:, 1])           

[2 5]


In [19]:
# Declaring two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])     
print(arr1)
print("********")
arr2 = np.array([[5, 6], [7, 8]])
print(arr2)

[[1 2]
 [3 4]]
********
[[5 6]
 [7 8]]


In [20]:
# Element-wise subtraction of two arrays
print(arr2-arr1)     

[[4 4]
 [4 4]]


In [21]:
# Element-wise addition of two arrays
print(arr2+arr1)     

[[ 6  8]
 [10 12]]


In [22]:
# Element-wise multiplication of two arrays
print(arr2*arr1)     


[[ 5 12]
 [21 32]]


In [23]:
# Element-wise division of two arrays
print(arr2/arr1)     

[[5.         3.        ]
 [2.33333333 2.        ]]


In [24]:
# Element-wise power operation
print(arr1**2)     

[[ 1  4]
 [ 9 16]]


In [25]:
print(arr1 @ arr2)  # Matrix multiplication between two arrays

[[19 22]
 [43 50]]


In [26]:
print(np.dot(arr1, arr2))   # Matrix multiplication between two arrays using dot
print("*" * 10)
print(arr1.dot(arr2))

[[19 22]
 [43 50]]
**********
[[19 22]
 [43 50]]


In [27]:
print(arr1.T)  # Transpose of an array

[[1 3]
 [2 4]]


In [28]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print("Index of the maximum element in arr3: ", np.argmax(arr3))                    # Index of the maximum element in the array
print("Index of the maximum element along the first axis in arr3: ", np.argmax(arr3, axis=0))    # Index of the maximum element along the first axis
print("Index of the maximum element along the second axis in arr3: ", np.argmax(arr3, axis=1))    # Index of the maximum element along the second axis

[[1 2 3]
 [4 5 6]]
Index of the maximum element in arr3:  5
Index of the maximum element along the first axis in arr3:  [1 1 1]
Index of the maximum element along the second axis in arr3:  [2 2]


In [29]:
# Differences between array and matrix in NumPy
import numpy as np
a_arr = np.array([1,2])
print("Shape of a in array form: ", a_arr.shape)
a_mat = np.mat([1,2])
print("Shape of a in matrix form: ", a_mat.shape)

Shape of a in array form:  (2,)
Shape of a in matrix form:  (1, 2)


In [30]:
# Transposing a matrix
mat_temp = np.mat([[1,2],[3,4]])
print("This matrix is:\n", mat_temp)
print('*' * 10)
print("Transpose of this matrix is:\n", mat_temp.T)

This matrix is:
 [[1 2]
 [3 4]]
**********
Transpose of this matrix is:
 [[1 3]
 [2 4]]


In [31]:
# Finding the inverse of a matrix
mat_temp = np.mat([[1,2],[3,4]])
print("This matrix is:\n", mat_temp)
print('*' * 10)
mat_inv = mat_temp.I
print("Inverse of this matrix is:\n", mat_inv)
print("Product of this matrix and its inverse is:\n", np.round(mat_temp.dot(mat_inv)))    # np.round is used to round the result to a specific number of decimal places

This matrix is:
 [[1 2]
 [3 4]]
**********
Inverse of this matrix is:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Product of this matrix and its inverse is:
 [[1. 0.]
 [0. 1.]]


In [32]:
equa = np.mat([[1,2,3],[4,5,6]])
print("This system of linear equations is:\n", equa)
print('*' * 10)
A = np.array([[1,2], [4,5]])   # 2x2 coefficient matrix
b = np.array([3,6])            # 2x1 matrix
res = np.linalg.solve(A, b)   # Solving the system of linear equations determined by the coefficient matrix
print("Solution to the system of linear equations is:\n", res.reshape(1,2).T)

This system of linear equations is:
 [[1 2 3]
 [4 5 6]]
**********
Solution to the system of linear equations is:
 [[-1.]
 [ 2.]]


In [33]:
equa = np.mat([[1,2,3],[4,5,6]])
print("This system of linear equations is:\n", equa)
print('*' * 10)
A = np.mat([[1,2], [4,5]])   # 2x2 coefficient matrix
b = np.mat([3,6]).T  # 2x1 matrix (must be in column vector form)
res = np.linalg.solve(A, b)   # Solving the system of linear equations determined by the coefficient matrix
print("Solution to the system of linear equations is:\n", res)

This system of linear equations is:
 [[1 2 3]
 [4 5 6]]
**********
Solution to the system of linear equations is:
 [[-1.]
 [ 2.]]
