## Random Forest

In [124]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_openml
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score

In [97]:
iris = load_iris()

In [98]:
x = iris.data
y = iris.target

In [100]:
print(x, y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [101]:
tree_clf = DecisionTreeClassifier()
tree_clf.fit(x, y)

tree_clf.feature_importances_

array([0.01333333, 0.01333333, 0.05072262, 0.92261071])

In [102]:
train_x, test_x,train_y, test_y = train_test_split(x, y, test_size=0.3, random_state=0)

tree_clf = DecisionTreeClassifier()
tree_clf.fit(train_x, train_y)

print(tree_clf.score(train_x, train_y))
print(tree_clf.score(test_x, test_y))

1.0
0.9777777777777777


In [163]:
dataset = fetch_openml(name='boston', version=1, as_frame=True, return_X_y=False, parser='pandas')

data = dataset['data']
target = dataset['target']

In [164]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.3, random_state=0)

tree_reg = DecisionTreeRegressor()
tree_reg.fit(x_train, y_train)

print('whole dataset train acc: {}'.format(tree_reg.score(x_train, y_train)))
print('whole dataset test acc: {}'.format(tree_reg.score(x_test, y_test)))

whole dataset train acc: 1.0
whole dataset test acc: 0.6402937851879762


In [165]:
def random_forest(x_train, y_train, x_test, y_test, drop_n=4):
    features_random = np.random.choice(list(x_train.columns), size=len(x_train.columns)-drop_n)

    x_sample = x_train[features_random]
    y_sample = y_train

    reg = DecisionTreeRegressor()
    reg.fit(x_sample, y_sample)

    score_train = reg.score(x_sample, y_sample)
    score_test = reg.score(x_test[features_random], y_test)

    print('sub sample :: train score: {}, test score: {}'.format(score_train, score_test))

    y_predicated = reg.predict(x_test[features_random])

    return y_predicated, score_test

In [170]:
random_forest(x_train, y_train, x_test, y_test, 4)

sub sample :: train score: 1.0, test score: 0.6155417954515938


(array([24.1, 25.1, 20.1,  9.6, 20.8, 25. , 22.7, 23.4, 22.6, 19.6,  7. ,
        11.9, 14.2, 10.2, 50. , 22.5, 21.8, 32.4, 28. , 20.9, 23.1, 16.1,
        18.5, 24.4, 22.2, 20.8, 19.4, 16.4, 33.4, 19.5, 12.6, 17.7, 24.5,
        22.2, 22.8, 17.7, 10.2, 25.1, 14.2,  9.5, 20.4, 22.5, 22. , 14.9,
        22. , 20.6, 19.8, 19.1, 14.4, 25. , 13.1, 22.4, 20. , 46.7, 15.6,
        22.4, 22.2, 17.5, 25.1, 20. , 24.1, 22.2, 27.9, 46.7, 17.7, 37. ,
        18.1, 14.5, 16.7, 22.2, 20.3, 25. , 34.9, 34.9, 25. , 10.2, 34.7,
        23.1, 28.4, 21.8, 22.2, 19.2, 22.6, 50. , 31.5, 25. , 28.4, 11.7,
        25. , 19.9, 22. , 11.8, 18.2, 22.5, 21.6, 28.7, 13.8, 30.1, 19. ,
        18.5, 22.4, 20.1, 27.5, 21.2, 22.2, 18.5,  8.8, 20.8, 23.9, 25.1,
        21.9,  9.5, 15.2,  7. , 14.5, 20. , 17.9, 18.4, 10.2, 42.3, 34.9,
        10.2, 19.8, 21.8, 18.9, 20.5, 33.2, 22.5, 20.9, 26.6, 15.1,  9.5,
        21.5, 19.6, 10.5, 24.5, 20. , 15.6, 24.4,  8.8, 13.3, 21.8, 28.7,
        22.2, 23.1, 14.5, 29.1, 32.5, 

In [171]:
with_feature_names = pd.DataFrame(data)
with_feature_names.columns = dataset['feature_names']

In [172]:
x_train, x_test, y_train, y_test = train_test_split(with_feature_names, target, test_size=0.3, random_state=0)

In [173]:
random_forest(x_train, y_train, x_test, y_test, 4)

sub sample :: train score: 1.0, test score: 0.21063694773920416


(array([24.8,  7.2, 20.6, 12.1, 22.9, 20.4, 12.7, 19. , 22.1, 23.1,  7. ,
        13.9, 16.1, 17.9, 50. , 34.9, 19.6, 34.6, 30.1, 19.3, 24.6, 20.8,
        19.5, 24.4, 16.2,  8.8, 14.5, 19.6, 43.8, 18.3, 14.1, 13.4, 24.7,
        20.5, 22. , 13.1, 10.2,  6.3, 17.1, 16.1, 21.7, 16.6, 36.2, 11.7,
        23.7, 24.2, 22.8, 24.3, 50. , 22.8, 23.8, 19.4, 20. , 41.7, 22. ,
        18.9, 17.4, 20.9,  5. , 24.7, 20.6, 17.8, 29.6, 28.4, 12. , 24.8,
        14.3, 23.4, 15. , 22.5, 24.6, 24.8, 22. , 37. , 26.5, 16.3, 43.8,
        23.1, 22. , 19.4, 23.9, 18. , 11.3, 37.6, 48.8, 23.4, 22.9, 11.8,
        27. , 19.1, 18.5,  9.6, 20.5, 34.9, 21.5, 16. , 11.9, 20.1, 16.4,
        17.6, 23.1, 22.4, 29.8, 22.8, 28.5, 18.9, 12.1, 13.1, 22.6, 24.4,
        29.8, 11.3, 25.3, 18.3, 17.4, 22.5, 12.7, 19.6, 13.8, 50. , 28. ,
        11.3, 16.2, 17.5, 19.7, 21.4, 32.7, 17.6, 20.7, 32.7, 16.7, 13.3,
        15.2, 23.8, 14.1, 34.6, 20. , 50. , 28. , 16.7, 10.2, 19.5, 29.9,
        22.2, 24.6, 15.6, 37.3, 37.3, 

In [174]:
tree_num = 4
predicates = []
for _ in range(tree_num):
    predicated, score = random_forest(x_train, y_train, x_test, y_test)
    predicates.append((predicated, score))

predicates_value = [v for v, s in predicates]
forest_scores = [s for v, s in predicates]

print('the mean result is: {}'.format(np.mean(predicates_value), axis=0))
print('the score of forest is: {}'.format(r2_score(y_test, np.mean(predicates_value, axis=0))))


sub sample :: train score: 1.0, test score: 0.7437817065239453
sub sample :: train score: 1.0, test score: 0.6108074154439198
sub sample :: train score: 1.0, test score: 0.5480721396412969
sub sample :: train score: 1.0, test score: 0.615563128605834
the mean result is: 21.49342105263158
the score of forest is: 0.7679782441332592


In [175]:
weights = np.array(forest_scores) / np.sum(forest_scores)
score_weights = np.zeros_like(np.mean(predicates_value, axis=0))

for i, v in enumerate(predicates_value):
    score_weights += v * weights[i]

print('the score of weighted forest is: {}'.format(r2_score(y_test, score_weights)))

the score of weighted forest is: 0.7739309396722459


![欢迎订阅：坍缩的奇点](../assets/Capture-2023-11-02-164446.png)