# PageRank

In [2]:
import numpy as np

In [3]:
# 设置转移矩阵
a = np.array([[0, 1/2, 1, 0], 
              [1/3, 0, 0, 1/2], 
              [1/3, 0, 0, 1/2], 
              [1/3, 1/2, 0, 0]])

a_leak = np.array([[0, 0, 0, 1/2], 
                   [0, 0, 0, 1/2], 
                   [0, 1, 0, 0], 
                   [0, 0, 1, 0]])

a_sink = np.array([[0, 0, 0, 0], 
                   [1/2, 0, 0, 1], 
                   [0, 1, 1, 0], 
                   [1/2, 0, 0, 0]])

b = np.array([1/4, 1/4, 1/4, 1/4])

w = b

In [4]:
def work(a, w):
  for i in range(100):
    # 每次求解 w, 是向量
    w = np.dot(a, w)
    print(w)

# n 代表网络中的 page 个数
def random_work(a, w, n):
  d = 0.85
  for i in range(100):
    # 随机浏览模型,让节点每次不会等于 0
    w = (1-d)/n + d*np.dot(a, w)
    print(w)

# work(a, w)
# work(a_sink, w)
# work(a_leak, w)
# random_work(a, w, 4)
random_work(a_leak, w, 4)
# random_work(a_sink, w, 4)

[0.14375 0.14375 0.25    0.25   ]
[0.14375   0.14375   0.1596875 0.25     ]
[0.14375    0.14375    0.1596875  0.17323437]
[0.11112461 0.11112461 0.1596875  0.17323437]
[0.11112461 0.11112461 0.13195592 0.17323437]
[0.11112461 0.11112461 0.13195592 0.14966253]
[0.10110658 0.10110658 0.13195592 0.14966253]
[0.10110658 0.10110658 0.12344059 0.14966253]
[0.10110658 0.10110658 0.12344059 0.1424245 ]
[0.09803041 0.09803041 0.12344059 0.1424245 ]
[0.09803041 0.09803041 0.12082585 0.1424245 ]
[0.09803041 0.09803041 0.12082585 0.14020197]
[0.09708584 0.09708584 0.12082585 0.14020197]
[0.09708584 0.09708584 0.12002296 0.14020197]
[0.09708584 0.09708584 0.12002296 0.13951952]
[0.0967958  0.0967958  0.12002296 0.13951952]
[0.0967958  0.0967958  0.11977643 0.13951952]
[0.0967958  0.0967958  0.11977643 0.13930996]
[0.09670673 0.09670673 0.11977643 0.13930996]
[0.09670673 0.09670673 0.11970072 0.13930996]
[0.09670673 0.09670673 0.11970072 0.13924562]
[0.09667939 0.09667939 0.11970072 0.13924562]
[0.0